<!DOCTYPE html>
<!--[if lt IE 7 ]><html class="ie ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html lang="ru"> <!--<![endif]-->

<head>
	<meta charset="utf-8">
	<title>Facebook Photobank: Actions of users</title>
	<meta name="description" content="">

	<link rel="shortcut icon" href="src/images/favicon/favicon.ico" type="image/x-icon">
	<link rel="apple-touch-icon" href="src/images/favicon/apple-touch-icon.png">
	<link rel="apple-touch-icon" sizes="72x72" href="src/images/favicon/apple-touch-icon-72x72.png">
	<link rel="apple-touch-icon" sizes="114x114" href="src/images/favicon/apple-touch-icon-114x114.png">

	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <link rel="stylesheet" href="src/libs/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="src/libs/animate/animate.css">

    <!--<link rel="stylesheet" href="src/css/bootstrap-skin.css">-->
	
	<link rel="stylesheet" href="src/css/fonts.css">
	<link rel="stylesheet" href="src/css/main.css">
	<link rel="stylesheet" href="src/css/media.css">

	<script src="src/libs/modernizr/modernizr.js"></script>

</head>

<body>

<header>
    <div class="row text-center">
        <h1 class="logo">Facebook Photobank: Actions of users</h1>
        <h4>Table of user actions</h4>
    </div>
</header>

<section class="container-fluid">

    <div class="row text-center">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <?php
                // Конектимся к нашей БД
                $link = mysql_connect("localhost", "root", "") or die("Could not connect : " . mysql_error());

                if( !mysql_select_db("tracker") ) {
                    // если БД нет, сообщим об этом
                    die("Could not select database");
                } else {
                    // выполняем SQL-запрос
                    $query = "SELECT * FROM events";
                    $result = mysql_query($query) or die("Query failed : " . mysql_error());

                    // выводим результаты в html
                    print '<div id = "events" class="panel panel-primary">';
                    print '<div class="panel-heading">Events</div>';
                    print '<table class="table">';
                    print '<thead><tr>';
                    print '<th>Event ID</th> <th>User ID</th> <th>User Name</th> <th>Event Type</th> <th>Event Element</th> <th>Event Element ID</th> <th>Event Time</th>';
                    print '</tr></thead>';
                    while ($line = mysql_fetch_array($result, MYSQL_ASSOC)) {
                        print '<tr>';
                        foreach ($line as $col_value) {
                        print "<td>$col_value</td>";
                        }
                        print "</tr>";
                    }
                    print '</table>';
                    print '</div>';

                    // освобождаем память от результата
                    mysql_free_result($result);
                }
                mysql_close($link);
            ?>
        </div>
    </div>

</section>

<footer>
    <div class="row text-center">
        <p>(с) 2015 All rights reserved</p>
    </div>
</footer>





	<div class="hidden"></div>

	<div class="loader">
		<div class="loader_inner"></div>
	</div>

	<!--[if lt IE 9]>
	<script src="src/libs/html5shiv/es5-shim.min.js"></script>
	<script src="src/libs/html5shiv/html5shiv.min.js"></script>
	<script src="src/libs/html5shiv/html5shiv-printshiv.min.js"></script>
	<script src="src/libs/respond/respond.min.js"></script>
	<![endif]-->

	<!--<script src="src/libs/jquery/jquery-1.11.2.min.js"></script>-->
    <script src="src/libs/jquery/jquery-2.1.4.min.js"></script>
    <script src="src/libs/bootstrap/js/bootstrap.min.js"></script>
    <script src="src/libs/waypoints/waypoints.min.js"></script>
    <script src="src/libs/animate/animate-css.js"></script>
    <script src="src/libs/plugins-scroll/plugins-scroll.js"></script>

    <script src="src/js/photobank.js"></script>
    <script src="src/js/common.js"></script>

</body>
</html>